FieldNotesWeb/Models/ViewModels/HomeViewModel.cs
using FieldNotesWeb.Models.Domain;

namespace FieldNotesWeb.Models.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<BlogPost> BlogPosts { get; set; }

        public IEnumerable<Tag> Tags { get; set; }


    }
}

FieldNotesWeb/Controllers/BlogsController.cs
using FieldNotesWeb.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace FieldNotesWeb.Controllers
{
    public class BlogsController : Controller
    {
        private readonly IBlogPostRepository blogPostRepository;

        public BlogsController(IBlogPostRepository blogPostRepository)
        {
            this.blogPostRepository = blogPostRepository;
        }


        [HttpGet]
        public async Task<IActionResult> Index(string urlHandle)
        {
            var blogPost = await blogPostRepository.GetByUrlHandleAsync(urlHandle);

            return View(blogPost);
        }
    }
}

FieldNotesWeb/Controllers/HomeController.cs
using FieldNotesWeb.Models;
using FieldNotesWeb.Models.ViewModels;
using FieldNotesWeb.Repositories;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FieldNotesWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IBlogPostRepository blogPostRepository;
        private readonly ITagRepository tagRepository;

        public HomeController(ILogger<HomeController> logger, IBlogPostRepository blogPostRepository, ITagRepository tagRepository)
        {
            _logger = logger;
            this.blogPostRepository = blogPostRepository;
            this.tagRepository = tagRepository;
        }

        public async Task<IActionResult> Index()
        {
            // getting all blogs
            var blogPosts = await blogPostRepository.GetAllAsync();

            // get all tags
            var tags = await tagRepository.GetAllAsync();

            var model = new HomeViewModel
            {
                BlogPosts = blogPosts,
                Tags = tags
            };

            return View(model);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FieldNotesWeb/Views/Home/Index.cshtml
@model FieldNotesWeb.Models.ViewModels.HomeViewModel

@{
    ViewData["Title"] = "Home Page";
}

<div class="container col-xxl-8 px-4 py-5">
    <div class="row align-items-center g-5 py-5">
        <div class="col-12 col-lg-6">
            <h1 class="display-5 fw-bold lh-1 mb-3">
                Field Notes - Synthesizing Everything
            </h1>
            <p class="lead">
                Hi! I'm Leo. I try to learn about anything and everything. This blog shows my notes.
            </p>
        </div>

        <div class="col-12 col-lg-6">
            <img src="https://images.pexels.com/photos/3779191/pexels-photo-3779191.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" alt="field notes images" class="d-bloc max-lg-auto img-fluid" width="300"/>
        </div>
    </div>
</div>


<div class="container">
    <div class="row justify-content-center">
        <div class="col-6 d-flex">
            @if (Model != null && Model.Tags.Any())
            {
                foreach(var tag in Model.Tags)
                {
                    <span class="badge bg-dark me-1">
                        @tag.Name
                    </span>
                }
            }
        </div>
    </div>
</div>


<div class="container">
    <div class="row justify-content-center">
        <div class="col-6">
            @if (Model != null && Model.BlogPosts.Any())
            {
                foreach(var blogPost in Model.BlogPosts)
                {
                    <div class="mb-5 bg-light box-shadow p-5">
                        <img src="@blogPost.FeaturedImageURL" alt="@blogPost.Heading" class="mb-2 d-block img-fluid"/>

                        <h2 class="mb-4">@blogPost.Heading</h2>

                        <p class="mb-2">
                            Author: @blogPost.Author
                            <br/>
                            Published Date: @blogPost.PublishedDate.ToShortDateString()
                        </p>

                        <p class="mb-2">
                            @foreach (var tag in blogPost.Tags)
                            {
                                <span class="badge bg-secondary me-1">@tag.Name</span>
                            }
                        </p>

                        <p class="mb-4">
                            @blogPost.ShortDescription
                        </p>

                        <a class="btn btn-dark" asp-area="" asp-controller="Blogs" asp-action="Index" asp-route-urlHandle="@blogPost.UrlHandle">Read More</a>
                    </div>
                }
            }
        </div>
    </div>
</div>